import {
  Award,
  Baby,
  Camera,
  Check,
  Circle,
  Clock,
  Compass,
  Flower2,
  Gift,
  Hand,
  HandHeart,
  Heart,
  Home,
  Laugh,
  MessageCircleHeart,
  Package,
  Palette,
  PartyPopper,
  ScrollText,
  Smile,
  Sparkles,
  Star,
  Trophy,
  Upload,
  Users,
  Utensils,
  Volume2,
} from "lucide-react";

const registry = {
  award: Award,
  baby: Baby,
  camera: Camera,
  check: Check,
  circle: Circle,
  clock: Clock,
  compass: Compass,
  flower: Flower2,
  gift: Gift,
  hand: Hand,
  handheart: HandHeart,
  heart: Heart,
  home: Home,
  laugh: Laugh,
  messageheart: MessageCircleHeart,
  package: Package,
  palette: Palette,
  party: PartyPopper,
  scroll: ScrollText,
  smile: Smile,
  sparkles: Sparkles,
  star: Star,
  trophy: Trophy,
  upload: Upload,
  users: Users,
  utensils: Utensils,
  volume: Volume2,
};

export function iconFor(name) {
  return registry[(name || "").toLowerCase()] ?? Camera;
}
